### ISSUE TITLE
How to generate RLE BWT format for paired-end illumina data

### ISSUE THREAD

**Issue by xinwang-bio** [holtjma/fmlrc#11]
Hi 
I have a paired-end illumina data in fastq format. I want to use it to correct the nanopore long reads using fmlrc. How to generate RLE BWT format using the X_1 and X_2 reads ?  Should I combine the X_1.fastq and X_2.fastq into one fastq file ?

Xin

**Comment by holtjma** [comment]
In short, yes the pairs are combined into a single read file.

The [example script](https://github.com/holtjma/fmlrc/blob/master/example/run_example.sh) does exactly what you're asking about on some relatively small E. coli data, so I would recommend mirroring that implementation.

**Comment by xinwang-bio** [comment]
Thanks a lot.
