### ISSUE TITLE
Question about final command

### ISSUE THREAD

**Issue by Tdanis** [holtjma/fmlrc#12]
Hello , so my question is about your final command 
./fmlrc [options] <comp_msbwt.npy> <long_reads.fa> <corrected_reads.fa>
                                                                                       ^^^^^^^^^^^^^^^^^^^
                                                                                      here we define the output?

**Comment by holtjma** [comment]
I'm not entirely sure I understand your question, but the main output of fmlrc (i.e. corrected reads) will be whatever filename you specify for `<corrected_reads.fa>`.

**Comment by Tdanis** [comment]
So here we specify the output file and before this the input file? Am I wrong?

Theodoros Danis

________________________________

**Comment by holtjma** [comment]
That's incorrect.  The things with brackets (<...>) are placeholders for your filenames.

If your BWT is at `/path/to/my/bwt/comp_msbwt.npy` AND
Your original reads are at `/path/to/my/sample/raw_reads.fa` AND
You want to store your output at `/path/to/my/sample/corrected_reads.fa` THEN
The full command would look like this:
```
./fmlrc /path/to/my/bwt/comp_msbwt.npy /path/to/my/sample/raw_reads.fa /path/to/my/sample/corrected_reads.fa
```

**Comment by Tdanis** [comment]
Thank you very much.
