### ISSUE TITLE
Index no output

### ISSUE THREAD

**Issue by AntoineHo** [holtjma/fmlrc#14]
Hello, I am trying to use the following command to build a comp_msbwt.npy file yet I have an error somewhere:

The command:
```bash
ilR1=input/filtered_Illumina_R1.fastq.gz
ilR2=input/filtered_Illumina_R2.fastq.gz
ropebwt2=/home/me/anaconda3/envs/fmlrc/bin/ropebwt2
fmlrc_convert=/home/me/anaconda3/envs/fmlrc/bin/fmlrc-convert
idx=out/path/comp_msbwt.npy
mkdir temp
pigz -p 20 -dc $ilR1 $ilR2 | awk 'NR % 4 == 2' | sort -T temp | tr NT TN | $ropebwt2 -LR | tr NT TN | $fmlrc_convert $idx
```

The output (the command runs yet no file appears in the /out/path directory) :
```bash
/out/path/comp_msbwt.npy: No such file or directory
```
Can it be due to the `sort` command? When I pipe until sort, no outputs appear in the terminal? The command is still running should I wait till the whole data is uncompressed?

Thanks a million :)

AH

**Comment by holtjma** [comment]
You wrote that `idx=out/path/comp_msbwt.npy` yet you appear to be searching for `/out/path/comp_msbwt.npy` (the difference is the leading `/`).  Can you verify that is not the issue?

**Comment by AntoineHo** [comment]
Hello, my mistake, I actually shortened the path in the issue for readability but the same path appears in the output as in the $idx variable, I made a test with `echo $idx` just before my command line. Here is the actual output:

```bash
/mnt/sda1/Antoine/29-11-19_Assembly/3_ErrorCorrection/comp_msbwt.npy
./assemble.sh: line 105: /mnt/sda1/Antoine/29-11-19_Assembly/3_ErrorCorrection/comp_msbwt.npy: No such file or directory
```

**Comment by holtjma** [comment]
Np, just trying to rule out the common issues.  Can you also verify the output directory already exists? (`/mnt/sda1/Antoine/29-11-19_Assembly/3_ErrorCorrection`).

I haven't used pigz before with this either, though I'm not sure if that would be an issue.

**Comment by AntoineHo** [comment]
No problem, thanks for the reactivity. Yes I did a `mkdir 3_ErrorCorrection` earlier in the script and I tried gunzip instead of pigz and had the same issue.

**Comment by holtjma** [comment]
Hmm might be time to try some basic debugging then; can you insert a “head -n 400” after the pigz command and progressively add the remaining steps?  If you can post where the output appears to fail I can help debug it more

**Comment by AntoineHo** [comment]
The first two steps (pigz and awk) yield these outputs :

EDIT: Sorry last comment was stupid I built up the command with head -n 400 until the fmlrc-convert command

The message about no such file or directory did not appear until I added `fmlrc-convert`.
Yet I get this output (which was not the case without the `head -n 400`):
```bash
./assemble.sh: line 107: /mnt/sda1/Antoine/29-11-19_VagaAssembly/3_ErrorCorrection/comp_msbwt.npy: No such file or directory
[M::mr_insert_multi] Turn off parallelization for this batch as too few strings are left.
[M::main_ropebwt2] inserted 24493 symbols in 0.010 sec, 0.009 CPU sec
[M::main_ropebwt2] constructed FM-index in 0.012 sec, 0.009 CPU sec
[M::main_ropebwt2] symbol counts: ($, A, C, G, T, N) = (100, 8622, 3815, 3656, 0, 8300)
```
There is no comp_msbwt.npy file in the output directory though...

EDIT2: I won't be available until tomorrow, thanks for the reactivity, cheers

**Comment by holtjma** [comment]
It seems like your script is trying to call the msbwt like an executable so I wonder if theres an issue with the fmlrc-convert pathing.  Can you try putting the full path (ie replace the variable $fmlrc_convert) and seeing what that gets you?

**Comment by AntoineHo** [comment]
Hello, it was indeed an error in the path... I feel stupid, I should have figured by myself.

Thank you for your help!
Cheers,

AH

**Comment by holtjma** [comment]
No worries, I've done that more times than I care to count.  Let me know if you have any more issues!
