### ISSUE TITLE
 ../fmlrc-convert: No such file or directory

### ISSUE THREAD

**Issue by qianxu05172019** [holtjma/fmlrc#18]
Hi,

I am trying to run the example, When I was running:
if [ ! -f ${DATADIR}/ecoli_comp_msbwt.npy ]; then
    mkdir temp
    gunzip -c ${DATADIR}/ERR022075_?.fastq.gz | awk "NR % 4 == 2" | sort -T ./temp | tr NT TN | ./ropebwt2/ropebwt2 -LR | tr NT TN | ../fmlrc-convert ${DATADIR}/ecoli_comp_msbwt.npy
fi

the output shows:  ../fmlrc-convert: No such file or directory

I looked at the path and I cannot find the binary file fmlrc-convert anywhere. Can you please help me with this?

**Comment by qianxu05172019** [comment]
Sorry, I forgot to compile the fmlrc...please delete this silly issue..

**Comment by holtjma** [comment]
No worries, let me know if you have any issues with fmlrc!

**Comment by qianxu05172019** [comment]
No problem, Thanks for this awesome tool!
