### ISSUE TITLE
Q: multiple round of flmrc2? 

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [holtjma/fmlrc#23]
Hello,

Thanks for your tool, it is really useful.

I am looking another layer of polishing as introduced by this other recent tool: HERO (https://github.com/kangxiongbin/HERO). They advise to run multiple round of flmrc2/rathatosk/lordec. Their tools is non working on my dataset requiring more than 3T of diskspace. I am now however wondering if running multiple round of flmrc2 is useful or make sense at all.

Do you have an advice/opinion on this?

Thanks,
Seb

**Comment by holtjma** [comment]
Seb,

This likely depends on how they're defining multiple rounds.  If they're talking about multiple k-mer sizes, then yes that makes sense.  FMLRC (this repo) only has support for two rounds (k / K in print).  FMLRC2 allows for any number of k-mer sizes, but that will come at a run-time cost.

If they're referring to running FMLRC2 multiple times with the same set of k-mers, I'm not really sure what that would improve.  In theory, if you ran it on the same `k` back-to-back, you wouldn't expect to find any changes.  I would expect that running FMLRC2 twice (or more) wouldn't have a significant impact on the results, but I could be wrong (I have not tested it and have not kept up with the research in the area).

Matt

**Comment by Sebastien-Raguideau** [comment]
Hi Matt,

Yes wrong repos....

Anyhow, they do indeed propose a sequential use of FLMRC2 back to back without change. I have run flmrc2 as they advise but didn't evaluate result and I suppose I would need to look at simulated dataset to get an accurate answer.

It sounds a bit like a legacy of racon/medaka workflow where racon was used multiple time in a row. I now realise that I should rather ask people from HERO. 

Thanks for the quick and enlightening answer.

Best,
Seb

**Comment by holtjma** [comment]
Yea no problem.  I can see how running with a k-mer pair (e.g., 21, 59) on repeat may slightly alter the answers, but it seems like it would be negligible compared to that first run. Anyways, let me know if you have any follow up questions!

Matt
